/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface BootcampInterface extends utils.Interface {
  functions: {
    "cid()": FunctionFragment;
    "courseImplementationAddress()": FunctionFragment;
    "courses(uint256)": FunctionFragment;
    "createCourse(string)": FunctionFragment;
    "getCourses()": FunctionFragment;
    "getImplementationAddress()": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "cid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "courseImplementationAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "courses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCourse",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCourses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getImplementationAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "cid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "courseImplementationAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "courses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCourse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCourses", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getImplementationAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "CourseCreated(address,address,string)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CourseCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type CourseCreatedEvent = TypedEvent<
  [string, string, string],
  { courseAddress: string; bootcamp: string; courseCID: string }
>;

export type CourseCreatedEventFilter = TypedEventFilter<CourseCreatedEvent>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  { previousOwner: string; newOwner: string }
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface Bootcamp extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BootcampInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    cid(overrides?: CallOverrides): Promise<[string]>;

    courseImplementationAddress(overrides?: CallOverrides): Promise<[string]>;

    courses(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    createCourse(
      _courseCID: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getCourses(overrides?: CallOverrides): Promise<[string[]]>;

    getImplementationAddress(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  cid(overrides?: CallOverrides): Promise<string>;

  courseImplementationAddress(overrides?: CallOverrides): Promise<string>;

  courses(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  createCourse(
    _courseCID: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getCourses(overrides?: CallOverrides): Promise<string[]>;

  getImplementationAddress(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    cid(overrides?: CallOverrides): Promise<string>;

    courseImplementationAddress(overrides?: CallOverrides): Promise<string>;

    courses(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    createCourse(
      _courseCID: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getCourses(overrides?: CallOverrides): Promise<string[]>;

    getImplementationAddress(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CourseCreated(address,address,string)"(
      courseAddress?: string | null,
      bootcamp?: string | null,
      courseCID?: null
    ): CourseCreatedEventFilter;
    CourseCreated(
      courseAddress?: string | null,
      bootcamp?: string | null,
      courseCID?: null
    ): CourseCreatedEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    cid(overrides?: CallOverrides): Promise<BigNumber>;

    courseImplementationAddress(overrides?: CallOverrides): Promise<BigNumber>;

    courses(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    createCourse(
      _courseCID: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getCourses(overrides?: CallOverrides): Promise<BigNumber>;

    getImplementationAddress(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    cid(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    courseImplementationAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    courses(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createCourse(
      _courseCID: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getCourses(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getImplementationAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
